theme: jekyll-theme-minimal
title: Astrometry.jl
description: Astrometry.jl is a set of IAU standard algorithms for calculating the time and position of celestial objects. More information can be found on the official website of the Standards of Fundamental Astronomy.
